name: Build Arma Server
on:
  push:
    branches: 
      - initial_development
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
     - uses: actions/checkout@v2
       timeout-minutes: 3
     - name: Run installer
       run: ./install-arma3server.sh
