name: Build Arma Server
on:
  push:
    branches: 
      - initial_development
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
     - uses: actions/checkout@v2
     - name: Run installer
       run: 
        ./install_arma_server.sh
     
