name: Build Arma Server
on:
  push:
    branches: 
      - initial_development
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
     - uses: actions/checkout@v1
     - name: Update VM
       run: sudo apt-get update -y
     - name: Run installer
        ./install_arma_server.sh
